import type { TrainerCardProps } from "@/types/Card";

export const mockTrainerCards: TrainerCardProps[] = [
  {
    id: "1",
    avatarFile: "이미지",
    name: "박재훈",
    description: "하체전문",
    commentsCount: 14,
    viewsCount: 512,
    votesCount: 120,
  },
  {
    id: "2",
    avatarFile: "이미지",
    name: "황철순",
    description: "상체전문",
    commentsCount: 8,
    viewsCount: 381,
    votesCount: 96,
  },
  {
    id: "3",
    avatarFile: "이미지",
    name: "김민수",
    description: "피지크",
    commentsCount: 21,
    viewsCount: 742,
    votesCount: 188,
  },
  {
    id: "4",
    avatarFile: "이미지",
    name: "우형재",
    description: "어깨전문",
    commentsCount: 5,
    viewsCount: 260,
    votesCount: 73,
  },
  {
    id: "5",
    avatarFile: "이미지",
    name: "이승철",
    description: "오픈",
    commentsCount: 11,
    viewsCount: 498,
    votesCount: 140,
  },
  {
    id: "6",
    avatarFile: "이미지",
    name: "이용승",
    description: "컨디셔닝",
    commentsCount: 4,
    viewsCount: 205,
    votesCount: 55,
  },
  {
    id: "7",
    name: "최한진",
    avatarFile: "이미지",
    description: "연예인PT",
    commentsCount: 13,
    viewsCount: 430,
    votesCount: 110,
  },
  {
    id: "8",
    name: "정대진",
    avatarFile: "이미지",
    description: "포징",
    commentsCount: 7,
    viewsCount: 312,
    votesCount: 84,
  },
  {
    id: "9",
    name: "장성엽",
    avatarFile: "이미지",
    description: "팔전문",
    commentsCount: 2,
    viewsCount: 151,
    votesCount: 33,
  },
  {
    id: "10",
    name: "김건우",
    avatarFile: "이미지",
    description: "등전문",
    commentsCount: 6,
    viewsCount: 289,
    votesCount: 67,
  },
  {
    id: "11",
    name: "김강민",
    avatarFile: "이미지",
    description: "스트렝스",
    commentsCount: 19,
    viewsCount: 803,
    votesCount: 201,
  },
];