import { ProteinCardProps } from "@/types/Card";

export const mockProteins: ProteinCardProps[] = [
  {
    id: "1",
    title: "마이프로틴 WPC",
    weight: "2.5kg",
    avatarFile: "",
    topic: "WPC",
    taste: "초코",
    price: "30,000원",
    likesCount: 123,
  },
  {
    id: "2",
    title: "마이프로틴 WPI",
    weight: "2.5kg",
    avatarFile: "",
    topic: "WPI",
    taste: "초코",
    price: "30,000원",
    likesCount: 123,
  },
  {
    id: "3",
    title: "다이마타이즈 엘리트 카제인",
    weight: "2.5kg",
    avatarFile: "",
    topic: "카제인",
    taste: "초코",
    price: "30,000원",
    likesCount: 123,
  },
  {
    id: "4",
    title: "옵티멈 골드",
    weight: "2.5kg",
    avatarFile: "",
    topic: "식물성",
    taste: "초코",
    price: "30,000원",
    likesCount: 123,
  },
  {
    id: "5",
    title: "컴뱃",
    weight: "2.5kg",
    avatarFile: "",
    topic: "WPI+WPC",
    taste: "초코",
    price: "30,000원",
    likesCount: 123,
  },
];
