import type { GymCardProps } from "@/types/Card";

export const mockGymsCards: GymCardProps[] = [
  {
    id: "1",
    title: "엔오엔짐",
    location: "경기 용인시 기흥구 석성로 257 1층",
    viewsCount: 341,
    postedAt: "2시간전",
    likesCount: 24,
  },
  {
    id: "2",
    title: "크로스핏 터틀",
    location: "경기 용인시 기흥구 구성로 176 삼광빌딩 B1",
    viewsCount: 341,
    postedAt: "2시간전",
    likesCount: 24,
  },
  {
    id: "3",
    title: "리가휘트니스",
    location: "경기 용인시 기흥구 언남동 259-7",
    viewsCount: 341,
    postedAt: "2시간전",
    likesCount: 24,
  },
  {
    id: "4",
    title: "재일짐",
    location: "경기 용인시 기흥구 구성로 102 푸른종합상가 2층 210호",
    viewsCount: 341,
    postedAt: "2시간전",
    likesCount: 24,
  },
  {
    id: "5",
    title: "빌리프짐",
    location: "경기 용인시 기흥구 구성로 103 상록멀티프라자 B1",
    viewsCount: 341,
    postedAt: "2시간전",
    likesCount: 24,
  },
  {
    id: "6",
    title: "하이클래스짐",
    location: "경기 용인시 기흥구 구성로 80 6층 7층",
    viewsCount: 341,
    postedAt: "2시간전",
    likesCount: 24,
  },
  {
    id: "7",
    title: "카인드짐",
    location: "경기 용인시 기흥구 죽전로 20 죽전누리에뜰 4층",
    viewsCount: 341,
    postedAt: "2시간전",
    likesCount: 24,
  },
  {
    id: "8",
    title: "한경국립대 지역문화복합관",
    location: "경기 안성시 중앙로 327 1층",
    viewsCount: 341,
    postedAt: "2시간전",
    likesCount: 24,
  },
  {
    id: "9",
    title: "스포데이 안성석정점",
    location: "경기 안성시 중앙로 274-36 라파엘빌딩 3층",
    viewsCount: 341,
    postedAt: "2시간전",
    likesCount: 24,
  },
];
