CREATE TYPE "public"."flavor_tier" AS ENUM('T1', 'T2', 'T3');--> statement-breakpoint
CREATE TABLE "protein_flavors" (
	"flavor_id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "protein_flavors_flavor_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"protein_id" bigint NOT NULL,
	"name" text NOT NULL,
	"tier" "flavor_tier",
	"polarizing" boolean DEFAULT false NOT NULL,
	"note" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "proteins" ADD COLUMN "url" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "protein_flavors" ADD CONSTRAINT "protein_flavors_protein_id_proteins_protein_id_fk" FOREIGN KEY ("protein_id") REFERENCES "public"."proteins"("protein_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "protein_flavors_unique_per_protein" ON "protein_flavors" USING btree ("protein_id","name");
ALTER TABLE public.protein_flavors
  ALTER COLUMN flavor_id SET GENERATED BY DEFAULT;