name: Create GitHub Release

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "릴리즈 PR을 생성할 브랜치"
        required: true
        default: "main"
  push:
    branches:
      - main
      - release/*

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-pr:
    if: >-
      github.event_name == 'workflow_dispatch' &&
      (
        github.event.inputs.target_branch == 'main' ||
        startsWith(github.event.inputs.target_branch, 'release/')
      )
    name: Release PR 생성
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: expo
          path: mobile
          skip-github-release: true
          target-branch: ${{ github.event.inputs.target_branch }}

  release:
    if: github.event_name == 'push'
    name: GitHub Release 생성
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: expo
          path: mobile
          skip-github-pull-request: true
          skip-github-release: false
          target-branch: ${{ github.ref_name }}
